# Generated by Django 4.2.5 on 2023-10-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopsy", "0003_category_remove_signup_mobile_signup_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="mobile",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_image", models.ImageField(upload_to="uploads/products/")),
                ("product_price", models.IntegerField()),
                (
                    "product_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopsy.category",
                    ),
                ),
            ],
        ),
    ]
