# Generated by Django 4.2.5 on 2023-10-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopsy", "0004_alter_signup_mobile_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
