# Generated by Django 4.2.5 on 2023-10-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopsy", "0005_signup_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
